languages: ["de", "en"]
name: Freifunk Köln, Bonn und Umgebung
wikilink: //kbu.freifunk.net/wiki/
maplink: http://map.kbu.freifunk.net/geomap.html
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data","smart"]
include: ['.htaccess']
highlighter: 'pygments'
image:
    source: _assets/images/original
    output: generated
    presets:
        medium:
            width: 300
            height: 260
